In [0]:
#Import libraries, mount Drive and load the dataset
import pandas as pd                 # package for data frame analysis
import matplotlib.pyplot as plt     # package for graphical plot
import seaborn as sns               # package for graphical plot
import numpy as np                  # package for mathematical calculation
from scipy import stats             # package for statistical calculation
import io                           # pakcage for input/output 
from google.colab import files      # package for Google drive manipulation
import geopy.distance

import warnings                     # disable warning notification (optional)
warnings.filterwarnings('ignore')
%matplotlib inline

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
data = pd.read_csv('/content/drive/My Drive/Data/trainmod2.csv')
data.head()

   Unnamed: 0                            key  fare_amount  ...  hour  year  distance
0           0  2009-06-15 17:26:21.000000100          4.5  ...    17  2009  1.030765
1           1  2010-01-05 16:52:16.000000200         16.9  ...    16  2010  8.450145
2           2  2011-08-18 00:35:00.000000490          5.7  ...     0  2011  1.389527
3           3  2012-04-21 04:30:42.000000100          7.7  ...     4  2012  2.799274
4           4  2010-03-09 07:51:00.000000135          5.3  ...     7  2010  1.999160

[5 rows x 11 columns]

In [0]:
#drop old ID and the 'key' since we have hour and year feature already
data = data.drop(columns = ['Unnamed: 0', 'key'])
data.head()

   fare_amount  pickup_longitude  pickup_latitude  ...  hour  year  distance
0          4.5        -73.844311        40.721319  ...    17  2009  1.030765
1         16.9        -74.016048        40.711303  ...    16  2010  8.450145
2          5.7        -73.982738        40.761270  ...     0  2011  1.389527
3          7.7        -73.987130        40.733143  ...     4  2012  2.799274
4          5.3        -73.968095        40.768008  ...     7  2010  1.999160

[5 rows x 9 columns]

In [0]:
#Check for value in the dropoff and pickup location
print(data['dropoff_longitude'].min())
print(data['dropoff_longitude'].max())
print(data['dropoff_latitude'].min())
print(data['dropoff_latitude'].max())
print(data['pickup_longitude'].min())
print(data['pickup_longitude'].max())
print(data['pickup_latitude'].min())
print(data['pickup_latitude'].max())

-3442.024565
3457.62235
-3547.886698
3537.132528
-3442.059565
3457.625683
-3492.263768
3408.789565

In [0]:
#The data contain strange value for the pick up and dropoff location
#Cleanup the data, keep the pickup and dropoff location close to New York City
df = data[data['pickup_longitude']<-74.3] 
data = data.drop(index = df.index)

In [0]:
df = data[data['pickup_longitude']>-73.6]
data = data.drop(index = df.index)

In [0]:
df = data[data['dropoff_longitude']>-72]
data = data.drop(index = df.index)

In [0]:
df = data[data['dropoff_longitude']<-76]
data = data.drop(index = df.index)

In [0]:
df = data[data['dropoff_latitude']<39.5]
data = data.drop(index = df.index)

In [0]:
df = data[data['dropoff_latitude']>42]
data = data.drop(index = df.index)

In [0]:
df = data[data['pickup_latitude']<40.49]
data = data.drop(index = df.index)

In [0]:
df = data[data['pickup_latitude']>40.92]
data = data.drop(index = df.index)

In [0]:
#Check for the value again
print(data['dropoff_longitude'].min())
print(data['dropoff_longitude'].max())
print(data['dropoff_latitude'].min())
print(data['dropoff_latitude'].max())
print(data['pickup_longitude'].min())
print(data['pickup_longitude'].max())
print(data['pickup_latitude'].min())
print(data['pickup_latitude'].max())

-75.98333199999998
-72.0
39.533332
41.998107
-74.3
-73.600002
40.4901
40.919967

In [0]:
data['distance'].max()

180.05226499999998

In [0]:
#Store into another csv file for Visualization and Prediction
data.to_csv('/content/drive/My Drive/Data/trainmod3.csv', index = False)